### ISSUE TITLE
CI failures due to incorrect setup

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.Witec#5] opened 2020-07-24 22:35 UTC
CI tests fail due to incorrect settings in `.github/workflows/pub_to_hySpc_pkgs.yml`:

![image](https://user-images.githubusercontent.com/12725868/88440549-f730e300-ce16-11ea-8024-daa0b720ce3b.png)

**Comment by bryanhanson** [comment] 2020-07-24 22:44
This is an obsolete workflow. Not sure why it is there.  Let me go look for the right one.

**Comment by bryanhanson** [comment] 2020-07-24 22:50
The correct one is in the same directory, it is called `build_check_deploy.yaml`.  Not sure why the one that causes the problem is there.  I think @eoduniyi should take a look, since he's been working on this repo.  He will have more info.

**Comment by cbeleites** [comment] 2020-07-29 15:25
CI seems to work again - should this issue be closed?

**Comment by GegznaV** [comment] 2020-07-29 15:38
Which pull request/commit solves this? 
***
**UPDATE:** issue fixed in #6 
~~And it seems that there is another issue related to CI:~~

<details>

![image](https://user-images.githubusercontent.com/12725868/88820888-96b0f580-d1ca-11ea-9d24-ce22ed556865.png)

</details>

**Comment by GegznaV** [comment] 2020-07-29 15:40
I'll try to update `pkgdown` setup when I have time for that. Recently, there were changes in the way GitHub Actions servers behave.

**Comment by bryanhanson** [comment] 2020-07-29 16:17
Depending up the branch there is a also a stale yaml.  @eoduniyi  can you take a look?

**Comment by GegznaV** [comment] 2020-07-29 20:25
Currently dir `".github/workflows/"` on `develop` branch contains 4 setup files:

1. "build_check.yaml"  
2. "build_check_deploy.yaml" 
3. "pub_to_hySpc_pkgs.yml" 
4. "pkgdown.yaml" 

The 4 is needed to build **pkgdown** website. And what are the purpose of the remaining 3? Which of them are obsolete?  
***
The following question: Why is only the combination of 'Linux' and `R-release`  used on GitHub Actions for R-CMD-check?

@eoduniyi, @bryanhanson

**Comment by bryanhanson** [comment] 2020-07-29 21:38
`build_check_deploy.yaml` is the script I have worked on. It works and should not be touched.  The others I will let @eoduniyi comment.

**Comment by GegznaV** [comment] 2020-08-05 10:11
@eoduniyi have you looked at this issue?

**Comment by eoduniyi** [comment] 2020-08-05 10:19
> `build_check_deploy.yaml` is the script I have worked on. It works and should not be touched. The others I will let @eoduniyi comment.

On it!!!

**Comment by GegznaV** [comment] 2020-08-05 10:21
@eoduniyi, when you close an issue, it would be better if this was linked to PR or commit that fixes the issue. It allows tracking what the solution was.

**Comment by GegznaV** [comment] 2020-08-11 12:58
@bryanhanson did you solve this in b5a02ab?

**Comment by bryanhanson** [comment] 2020-08-11 13:27
No, it was actually fixed in https://github.com/r-hyperspec/hySpc.read.txt/commit/5b3c09e736b1e64dea933d2c958c81efa007d6f6  Thanks for the reminder.

**Closed as completed by bryanhanson** 2020-08-11 13:27 UTC
